name: Build and Publish
on: 
  push:
    branches:
      - publish-package-workflow # TODO: Remove after validating
      - main
jobs:
  build:
    uses: elastic-ipfs/core-lib/.github/workflows/package-shared-build.yaml@publish-package-workflow # TODO: Change this to 'main'
    with:
      npm_push: true
    secrets:
      NPM_TOKEN: ${{ secrets.NPM_TOKEN }}